DELETE  http://localhost:8080/contribute/artist/a300f275-a816-4681-8e69-2027ca9f39c3
Content-Type: application/json
Cookie: session_id=O+QVNPYIRa9CyUbph9BkX6979tUA2ayLd1vLa7H3YlZbOT0dPOX+VSWpIdqidLRoD1oEqvaVNGu3f1vVT%2FXoMe9ugl26+796IXvdi1NmhgEb2Q%3D%3D;
