DELETE  http://localhost:8080/contribute/artist/4d171119-0ff4-4fd2-b75e-614f20221bbe
Content-Type: application/json
Cookie: session_id=JGq3bBcGn6JlrRY0wIPgFDqjV9vgsqmP8paooZmkE0TIKii6itFESn1eGVxTOT6EuymK4CRPk0Mqo0vNvVOw3hAmKH%2FF1ZRrAFAhplShNpIlAQ%3D%3D;
