[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.8.0"
chrono = { version = "0.4.38", features = ["serde"] }
dotenvy = "0.15.7"
env_logger = "0.11.3"
log = "0.4.22"
mimalloc = "0.1.43"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.120"
slug = "0.1.6"
tokio = { version = "1.38.1", features = ["full"] }
unidecode = "0.3.0"
uuid = { version = "1.10.0", features = ["v4"] }
validate = "0.6.1"
validator = { version = "0.18.1", features = ["derive"] }

[dependencies.sqlx]
version = "0.7.4"
features = [
    "runtime-tokio",
    "chrono",
    "uuid",
    "postgres",
    "macros",
    "tls-native-tls",
]
