[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.6"
actix-session = { version = "0.10.1", features = ["cookie-session"] }
actix-web = { version = "4.9.0", default-features = false, features = [
  "cookies",
  "macros",
  "compress-gzip",
] }
base64 = "0.22.1"
bcrypt = "0.15.1"
chrono = { workspace = true }
domain-proc-macros = { path = "../domain-proc-macros" }
dotenvy = "0.15.7"
env_logger = "0.11.5"
futures = "0.3.31"
log = "0.4.22"
mimalloc = "0.1.43"
serde = { workspace = true }
serde_json = { workspace = true }
slug = "0.1.6"
sqlx = { version = "0.8.2", default-features = false, features = [
  "runtime-tokio",
  "chrono",
  "uuid",
  "postgres",
  "macros",
  "tls-native-tls",
  "json",
] }
tokio = { workspace = true }
unidecode = "0.3.0"
uuid = { workspace = true }
validator = { version = "0.19.0", features = ["derive"] }
