[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-session = { version = "0.10.1", features = ["cookie-session"] }
actix-web = "4.9.0"
base64 = "0.22.1"
bcrypt = "0.15.1"
chrono = { version = "0.4.38", features = ["serde"] }
dotenvy = "0.15.7"
env_logger = "0.11.5"
log = "0.4.22"
mimalloc = "0.1.43"
serde = { version = "1.0.213", features = ["derive"] }
serde_json = { version = "1.0.132", features = ["preserve_order"] }
slug = "0.1.6"
tokio = { version = "1.41.0", features = ["full"] }
unidecode = "0.3.0"
uuid = { version = "1.11.0", features = ["v4"] }
validator = { version = "0.18.1", features = ["derive"] }
sqlx = { version = "0.8.2", features = [
    "runtime-tokio",
    "chrono",
    "uuid",
    "postgres",
    "macros",
    "tls-native-tls",
] }
actix-files = "0.6.6"
derive_builder = "0.20.2"
domain-proc-macros = { path = "../domain-proc-macros" }
