$schema: https://spec.openapis.org/oas/3.1/schema/2022-10-07
openapi: 3.1.0
info:
  title: Pubby Disco API
  version: 0.1.0
components:
  schemas:
    CreateGenreDTO:
      type: object
      required:
        - name
      properties:
        name:
          type: string

        parent_id:
          type: string
paths:
  "/login":
    post:
      operationId: login
      description: Login to the API
      summary: Login to the API
      tags:
        - User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
