DELETE   http://localhost:8080/contribute/media/6b88ae4f-c7ac-49b8-abf2-38a65f8e17f1
Content-Type: application/json
Cookie: session_id=05LWZe9BfERiHRkeU2EClUiErQorbgBmFklAHwOU%2FckiuXU8%2FCLLX1YrayM2PYvx6IRWzdXkqeBAdJsXWrRbrILp1rBtmbJoOnYqgmMuACXaTg%3D%3D;