[package]
name = "application"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../shared" }
domain = { path = "../domain" }
ports = { path = "../ports" }
validator = { workspace = true }
serde = { workspace = true }
chrono = { workspace = true }
