PATCH  http://localhost:8080/activities/approve
Content-Type: application/json
Cookie: session_id=jBRY34Z+I+N21bDlQ1xg4yqdngIUVSvhMP54wRHQSCn74f6V88pkauG+0X7dLZsRZAhAn2dVTfu8OQD2tSJF7XnVzqGkP19G9v6xcqe1oFZRMg%3D%3D;

{
  "activity_id": "07442ff1-777c-4df8-828b-b401c7f553d6"
}