PATCH  http://localhost:8080/activities/56912231-f4f3-4c12-b9f6-40b8e0311972/approve
Content-Type: application/json
Cookie: session_id=dLAifdsIgJElpEUiRtBB5ldzhDPZjqnh0FUq65t0aJBBFJAzTvbKXMTLQJ70j1X6SRyxxmoVtc5bf0Jj3FGtJHZt2TIE05pxcDF6MFmKPLVwXw%3D%3D;

