PATCH  http://localhost:8080/activities/4a2c0a81-ce17-4bb0-b128-cbc1a75f487b/approve
Content-Type: application/json
Cookie: session_id=V1b3Bdhb8TQLJAqsnlWVFlDqv0xWAeCZVuYRJgdvk0b6z46nklkTbQq2IwLrIrIjD3cVzDsIM+%2F4W72li0cZBCl2NE7POnokG111p7VZMIKZRw%3D%3D;