POST http://localhost:8080/activities
Content-Type: application/json
Cookie: session_id=s95OHVHI0lg8cyk3U71vD9VVlmW6bPdwWXcLEJ1iVHAt0+FfDwViynepcrlrhfKNMkFSSyy6%2FM+AD+iveOlkEFrEIbslDf088aYcrvdx1rePhZ0OoXjnPrl%2Fr0%2FiYozBsxIHblzEA%2FK31k2pDxFgP1jhYA5eL2SSHShdXctZCKBei3hkoUdALe%2F6jFmL;

{
  "Create": {
    "Artist": {
      "name": "Michael Jackson",
      "slug": "michael-jackson",
      "country": "USA"
    }
  }
}