PATCH  http://localhost:8080/activities/reject
Content-Type: application/json
Cookie: session_id=S%2F8OiycBnr4F4VZGo5V7HA5Rkd29cwEkRE8Boj3nPm7IhYv6h7F9q2iZPt865lLXsQBYceTozG+bdNI1%2FGZ%2FqoCQ3TBGHagsxFM3Dl8IyJ%2FPwK+WRHyWbTXjLF62mafACvfv100+nP5q06WjbzpqCVqUS9H5k4S5OQkIwRTr0sBzEG1xC08GNMvd0+cY;

{
  "activity_id": "06a79f94-8849-4b25-ac57-315e5b0774c8",
  "reason": "I don't like this activity"
}