PATCH  http://localhost:8080/activities/471da231-c150-45bb-90da-82c3d9b31951/reject
Content-Type: application/json
Cookie: session_id=V1b3Bdhb8TQLJAqsnlWVFlDqv0xWAeCZVuYRJgdvk0b6z46nklkTbQq2IwLrIrIjD3cVzDsIM+%2F4W72li0cZBCl2NE7POnokG111p7VZMIKZRw%3D%3D;

{
  "reason": "I don't like this activity"
}